FROM docker.io/node:trixie

RUN apt-get update && apt-get install -y --no-install-recommends xdg-utils && rm -rf /var/lib/apt/lists/*

RUN npm install -g opencode-ai

RUN npm install -g agent-browser

ENV OPENCODE_CONFIG_DIR /etc/opencode

RUN mkdir -p /etc/opencode

EXPOSE 4096

ENTRYPOINT ["opencode", "web", "--hostname", "0.0.0.0", "--port", "4096"]
