events {}

http {
  server {
    server_name example.com;

    location / {
      proxy_pass http://127.0.0.1:8080/guacamole;
    }

    location /mcp/ {
      proxy_pass http://127.0.0.1:8000/;
    }

    listen 80;
  }
}
