events {}

http {
  server {
    server_name __SERVER_NAME__;

    location = / {
      return 301 /guacamole/;
    }

    location /guacamole/ {
      proxy_pass http://127.0.0.1:8080/guacamole/;
    }

    location / {
      proxy_pass http://127.0.0.1:8000;
    }

    listen 80;
  }
}
