#!/usr/bin/env bash

set -e

[ -z "$1" ] && { echo "Usage: $0 <host>"; exit 1; }

HOST=$1

ssh $HOST 'sudo apt purge docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin docker-ce-rootless-extras'

ssh $HOST 'sudo rm -rf /var/lib/docker; sudo rm -rf /var/lib/containerd;'

ssh $HOST 'sudo rm /etc/apt/sources.list.d/docker.sources; sudo rm /etc/apt/keyrings/docker.asc;'
