name: Install

on:
  push:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-24.04
    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v7

      - name: Project name
        run: 'sed -i "s/name: amish/name: amish-ci/" deploy.template.yaml'

      - name: Run deploy script
        run: doctl apps create --spec .do/deploy.template.yaml --wait

      - name: Cleanup
        run: doctl apps delete $(doctl apps list | grep amish | awk '{ print $1 }') --force
